#!/bin/bash
# https://github.com/termux/termux-widget
# For backing up receipts, licenses, manuals, etc.
# Prompts to move latest file in the DCIM dir to somewhere in backup docs.

dcim_dir="$HOME/storage/dcim/Camera"
docs_dir="$HOME/storage/shared/backup/docs"

latest_file="$(ls -1t "$dcim_dir" | head -n 1)"

fail() {
	echo "$1 Exiting." >&2
	exit 1
}

[ -f "$dcim_dir/$latest_file" ] || fail "$latest_file is not a file."

echo "Move $latest_file to?"
read -e -r -i "$docs_dir/" dest

# replace all spaces with underscores
dest="${dest// /_}"

# append extension if missing
ext="${latest_file##*.}"
[[ $dest == *.$ext ]] || dest="$dest.$ext"

[ -n "$dest" ] || fail "No destination."
[ ! -e "$dest" ] || fail "Destination already exists."

mv "$dcim_dir/$latest_file" "$dest"

printf 'Moved to %s\nPress Enter...' "$dest"
read _
