#!/bin/bash
# https://github.com/termux/termux-widget
# For backing up receipts, licenses, manuals, etc.
# Prompts to move latest file in the DCIM dir to somewhere in backup docs.

dcim_dir="$HOME/storage/dcim/Camera"
docs_dir="$HOME/storage/shared/backup/docs"

latest_file="$(find -L "$dcim_dir" -type f -name '*.jpg' -printf '%T@ %P\n' \
	| sort -r \
	| head -n1 \
	| awk '{print $2}')"

fail() {
	echo "$1 Exiting." >&2
	exit 1
}

[[ -f "$dcim_dir/$latest_file" ]] || fail "$latest_file is not a file."

while [[ -z $dest ]] || [[ -d $dest ]]; do
	echo "Move $latest_file to? (spaces and ext will be fixed)"
	read -eri "$docs_dir/" dest
done

# replace all spaces with underscores
dest="${dest// /_}"
# append extension if missing
ext="${latest_file##*.}"
[[ $dest == *.$ext ]] || dest="$dest.$ext"

if [[ -e "$dest" ]]; then
	read -rp "$dest exists. Continue? " -ei 'n'
	[[ $REPLY =~ [Yy].* ]] || exit 1
fi

read -rp 'Compress to percentage? (Empty skips) ' -ei 5% quality
if [[ -n $quality ]]; then
	magick "$dcim_dir/$latest_file" -quality "$quality" "$dest" \
		|| fail 'No changes were made.'
else
	cp "$dcim_dir/$latest_file" "$dest"
fi

echo "Opening for preview $dest"
termux-share "$dest"

read -rp "Delete original $latest_file? " -ei 'y'
[[ $REPLY =~ [nN].* ]] || rm "$dcim_dir/$latest_file"

read -rp 'Press Enter...'
