#!/bin/bash
# https://github.com/termux/termux-widget
# Prompt to edit a file

# The -e gets input from readline so tab completion will work
read -eri "vim '+cd %:h' ~/storage/shared/backup/docs/"
bash -c "$REPLY"
