#!/bin/bash

# Add an entry to ledger.csv that has 4 columns:
# Date,Amount,Description,Categories
# Categories can be used to group rows;
# multiple categories for the same entry are separated by spaces.
# Later you can make some fancy awk scripts for the csv to build reports.

csv="$HOME/storage/shared/backup/docs/ledger.csv"
date=
amount="-"
description=
categories=

[ -f "$csv" ] || { echo "No $csv" >&2; exit 1; }

while [[ ! "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; do
	read -rp "Date: " -i "$(date +%Y-%m-%d)" date
done

while [[ ! "$amount" =~ ^[+-]?[0-9]+(\.[0-9]+)?$ ]]; do
	read -rp "Amount: $" -i "$amount" amount
done

while [[ ! "$description" =~ ^[^,]+$ ]]; do
	read -rp "Description (no commas): " -i "$description" description
done

existing_categories="$(awk -F, 'NR>1{print $4}' "$csv" \
	| tr ' ' '\n' \
	| sort --ignore-case \
	| uniq --ignore-case \
	| paste -sd' ')"
while [[ ! "$categories" =~ ^[a-z0-9\ ]+$ ]]; do
	read -rp "Categories ($existing_categories): " \
		-i "$categories" categories
done

echo "$date,$amount,$description,$categories" >> "$csv"

column -ts, "$csv" | sort -n | less -S +G
