#!/bin/bash
# https://github.com/termux/termux-widget
# Add an entry to ledger.csv that has 4 columns:
# Date,Amount,Description,Category
# Categories can be used to group rows.
# Later you can make some fancy awk scripts for the csv to build reports.

csv="$HOME/storage/shared/backup/docs/ledger.csv"
date=
amount="-"
description=
category=

[ -f "$csv" ] || { echo "No $csv" >&2; exit 1; }

while [[ ! "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; do
	read -erp "Date: " -i "$(date +%Y-%m-%d)" date
done

while [[ ! "$amount" =~ ^[+-]?[0-9]+(\.[0-9]+)?$ ]]; do
	read -erp "Amount: $" -i "$amount" amount
done

while [[ ! "$description" =~ ^[^,]+$ ]]; do
	read -erp "Description (no commas): " -i "$description" description
done

existing_categories="$(awk -F, 'NR>1{print $4}' "$csv" \
	| tr ' ' '\n' \
	| sort --ignore-case \
	| uniq --ignore-case \
	| paste -sd' ')"
while [[ ! "$category" =~ ^[a-z0-9]+$ ]]; do
	read -erp "Category ($existing_categories): " -i "$category" category
done

echo "$date,$amount,$description,$category" >> "$csv"

column -ts, "$csv" | sort -n | less -S +G
