#!/bin/bash
# https://github.com/termux/termux-widget

default_t=0m  # no timeout

read -erp "Timeout? " -i "$default_t" t
[ -z "$t" ] && t="$default_t"

cd ~/storage/shared/backup/audio || exit

find . -type d -printf "%P/\n" \
	, -type f -printf "%P\n" \
	| sed '1s/^/./' \
	| awk '{print length, $0}' \
	| sort -n \
	| sed 's/^[0-9]* //' \
	| nvim -N -R -M -u <(echo "
set nowrap
set sidescrolloff=10
set mouse=a
set hlsearch incsearch
set ignorecase smartcase

syntax on
match Comment /.*\/$/

map q :q<CR>
map <CR> :!timeout --foreground $t mpv
	\ <C-R>=shellescape(getline('.'))<CR><CR>
") -
