#!/bin/bash
# https://github.com/termux/termux-widget

cd ~/storage/shared/backup/audio || exit

f="$(find . -printf "%d %p\n" \
	| sort -n \
	| sed 's/^[0-9]\+ //' \
	| fzf --exact)"

[ -z "$f" ] && exit

timeout --foreground 30m mpv "$f"
