#!/bin/sh
# https://github.com/termux/termux-widget
# https://wiki.termux.com/wiki/Remote_Access

echo 'Starting sshd...'
sshd || exit

address="$(ifconfig 2>/dev/null|grep -A1 wlan0|grep 'inet '|awk '{print $2}'|cut -d / -f 1)"
printf "\nTo connect: ssh -p 8022 %s@%s\n\n" "$(whoami)" "$address"

printf 'Press Enter to end the process...'
read _
killall sshd
