#!/bin/sh
# https://github.com/termux/termux-widget
# https://wiki.termux.com/wiki/Remote_Access

echo 'Starting sshd...'
sshd || exit

user="$(whoami)"
address="$(ifconfig 2>/dev/null|grep -A1 wlan0|awk '/inet/{print $2}')"
port=8022
printf "\nTo connect: ssh -p %s %s@%s" "$port" "$user" "$address"
printf "\nTo copy:    scp -P %s -r ..." "$port"
printf "\nTo sftp:    sftp -P %s ..." "$port"
printf "\n\n"

fingerprints="$(cat "$PREFIX"/etc/ssh/ssh_host_*.pub | ssh-keygen -lf -)"
printf "Fingerprints:\n%s" "$fingerprints"

printf "\n\nAcquiring wakelock..."
termux-wake-lock

printf '\n\nPress Enter to end the process...'
read -r _

printf "\nReleasing wakelock..."
termux-wake-unlock

killall sshd
